name: Deploy to GitHub Pages

on: [workflow_dispatch, push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fetch_jsons:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        # I just fetch the data for building the tables/maps here an commit to repo, just in case
        - name: fetch jsons from entity repo
          run: |
            if [ ! -d ./src/jsons ]
            then
              mkdir ./src/jsons
            fi
            curl https://raw.githubusercontent.com/NestroyCA/baserow-entities/main/json_dumps/lemma_context.json -o ./src/jsons/lemma_context.json
        - name: commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: fetched json files
