name: Deploy to GitHub Pages

on: [workflow_dispatch, push]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  PUBLIC_APP_BASE_URL: https://nestroyca.acdh-dev.oeaw.ac.at
  # PUBLIC_APP_BASE_URL:
  PUBLIC_REDMINE_ID: 21437

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      # I just fetch the data for building the tables/maps here an commit to repo, just in case
      - name: fetch jsons from entity repo
        run: |
          curl -o ./public/jsons/nestroyvienna.json https://raw.githubusercontent.com/NestroyCA/baserow-entities/main/json_dumps/vienna_places_tabulator.json"
          curl -o ./public/jsons/places.json https://raw.githubusercontent.com/NestroyCA/baserow-entities/main/json_dumps/places_tabulator.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Exported and Transformed EMT-Transkribus Collections
      - name: Install, build, and upload your site
        uses: ./.github/actions/setup_astro
        with:
          path: .
          node-version: 16
          package-manager: pnpm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
